### ISSUE TITLE
How to make a PluginParameter unrequired

### ISSUE THREAD

**Issue by yum-yab** [dbpedia/cmem-plugin-databus#2]
To my understanding building a `PluginParameter` like this
```
PluginParameter(
            name="version",
            label="Dataset Version",
            description="The version of the Dataset. If omitted, it is automatically set to YYYY.MM.DD. NOTE: This "
                        "can overwrite already published Datasets on the Databus!",
        ),
```
makes it not required, setting the parameter in the class to `None`. But this was not working in cmem-plugin-databus, since it still required a version.

Things that did not work:
* setting the `default_value` to `None`
* setting the `default_value` to `""`
* letting the `default_value` unassigned

So how to make it not required?

**Comment by robertisele** [comment]
In order to make a parameter optional you would set the default_value. In your case, as this is a string, you would set something like `default_value = "my default value"`. Could you elaborate how this didn't work? I tried it with another plugin and I could create an instance in the UI without setting a value for that parameter.

Instead of setting the default_value on PluginParameter you can also set it directly in the init method (e.g. `def __init__(
        self, version = "my default value"`), which will automatically transfer this to the PluginParameter .

**Comment by yum-yab** [comment]
Issue seems resolved, thanks for the answer :)
